import type { Booking, SalonProfile, Service, StaffMember } from "./types";

export const salon: SalonProfile = {
  name: "Prime Glow Studio",
  tagline: "Modern beauty appointments without the back-and-forth messages.",
  address: "Rizal Street, Legazpi City, Albay",
  phone: "0917 123 4567",
  email: "hello@primeglow.test",
  openingHours: "Monday to Saturday, 9:00 AM – 7:00 PM",
};

export const services: Service[] = [
  {
    id: "haircut-blowdry",
    name: "Haircut & Blow Dry",
    description: "A clean shape refresh finished with a soft blow dry and style.",
    category: "Hair",
    price: 450,
    durationMinutes: 60,
    isActive: true,
  },
  {
    id: "hair-color",
    name: "Full Hair Color",
    description: "Single-process color service with consultation and aftercare advice.",
    category: "Color",
    price: 1800,
    durationMinutes: 150,
    isActive: true,
  },
  {
    id: "keratin-treatment",
    name: "Keratin Smoothing",
    description: "Frizz-control treatment for smoother, shinier, easier-to-manage hair.",
    category: "Treatment",
    price: 2500,
    durationMinutes: 180,
    isActive: true,
  },
  {
    id: "manicure-gel",
    name: "Gel Manicure",
    description: "Cuticle care, nail shaping, gel polish, and glossy finish.",
    category: "Nails",
    price: 650,
    durationMinutes: 75,
    isActive: true,
  },
  {
    id: "event-makeup",
    name: "Event Makeup",
    description: "Soft glam makeup for graduations, birthdays, photoshoots, and events.",
    category: "Makeup",
    price: 1200,
    durationMinutes: 90,
    isActive: true,
  },
  {
    id: "hair-spa",
    name: "Signature Hair Spa",
    description: "Relaxing treatment focused on moisture, shine, and scalp comfort.",
    category: "Treatment",
    price: 850,
    durationMinutes: 75,
    isActive: true,
  },
];

export const staffMembers: StaffMember[] = [
  {
    id: "mika-reyes",
    name: "Mika Reyes",
    role: "Senior Hair Stylist",
    bio: "Specializes in layered cuts, soft waves, and everyday styling.",
    services: ["haircut-blowdry", "hair-color", "hair-spa"],
  },
  {
    id: "isabelle-cruz",
    name: "Isabelle Cruz",
    role: "Color Specialist",
    bio: "Focused on rich color, gloss treatments, and hair repair services.",
    services: ["hair-color", "keratin-treatment", "hair-spa"],
  },
  {
    id: "lara-santos",
    name: "Lara Santos",
    role: "Beauty Artist",
    bio: "Handles makeup, nails, and polished event-ready beauty looks.",
    services: ["event-makeup", "manicure-gel"],
  },
];

export const bookings: Booking[] = [
  {
    id: "bk-001",
    customerName: "Angela Dela Cruz",
    customerPhone: "0918 222 3344",
    serviceId: "haircut-blowdry",
    staffId: "mika-reyes",
    date: new Date().toISOString().slice(0, 10),
    startTime: "09:30",
    endTime: "10:30",
    status: "confirmed",
  },
  {
    id: "bk-002",
    customerName: "Trisha Mendoza",
    customerPhone: "0927 555 1199",
    serviceId: "hair-color",
    staffId: "isabelle-cruz",
    date: new Date().toISOString().slice(0, 10),
    startTime: "11:00",
    endTime: "13:30",
    status: "pending",
    notes: "Warm brown tone, not too light.",
  },
  {
    id: "bk-003",
    customerName: "Kath Ramos",
    customerPhone: "0995 333 1188",
    serviceId: "event-makeup",
    staffId: "lara-santos",
    date: new Date().toISOString().slice(0, 10),
    startTime: "14:30",
    endTime: "16:00",
    status: "confirmed",
  },
  {
    id: "bk-004",
    customerName: "Bea Villanueva",
    customerPhone: "0916 888 7022",
    serviceId: "manicure-gel",
    staffId: "lara-santos",
    date: new Date().toISOString().slice(0, 10),
    startTime: "16:30",
    endTime: "17:45",
    status: "completed",
  },
];
